#ifndef MEMORYSWITCHERPLUGIN_GLOBAL_H
#define MEMORYSWITCHERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MEMORYSWITCHERPLUGIN_LIB
# define MEMORYSWITCHERPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define MEMORYSWITCHERPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // MEMORYSWITCHERPLUGIN_GLOBAL_H
