#ifndef PLAINTEXTLOGGERPLUGIN_GLOBAL_H
#define PLAINTEXTLOGGERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PLAINTEXTLOGGERPLUGIN_LIB
# define PLAINTEXTLOGGERPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define PLAINTEXTLOGGERPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // PLAINTEXTLOGGERPLUGIN_GLOBAL_H
