#ifndef IMAGEPIXELADDERPLUGIN_GLOBAL_H
#define IMAGEPIXELADDERPLUGIN_GLOBAL_H

#include <QGlobal.h>

#ifdef IMAGEPIXELADDERPLUGIN_LIB
# define IMAGEPIXELADDERPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define IMAGEPIXELADDERPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGEPIXELADDERPLUGIN_GLOBAL_H
