# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./BasicPayOff.h \
    ./GEquationPayOff.h \
    ./GMonteCarloLogNormalPricer.h \
    ./GMonteCarloLogNormalPricerWidget.h \
    ./GPayOff.h \
    ./MonteCarloLogNormalPricerPlugin.h \
    ./MonteCarloLogNormalPricerPlugin_global.h
SOURCES += ./BasicPayOff.cpp \
    ./GEquationPayOff.cpp \
    ./GMonteCarloLogNormalPricer.cpp \
    ./GMonteCarloLogNormalPricerWidget.cpp \
    ./GPayOff.cpp \
    ./MonteCarloLogNormalPricerPlugin.cpp
FORMS += ./GMonteCarloLogNormalPricerWidget.ui
