#ifndef FITTER2DGAUSSIANPLUGIN_GLOBAL_H
#define FITTER2DGAUSSIANPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FITTER2DGAUSSIANPLUGIN_LIB
# define FITTER2DGAUSSIANPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define FITTER2DGAUSSIANPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // FITTER2DGAUSSIANPLUGIN_GLOBAL_H
