#ifndef PLUGINCAMERAUEYE_GLOBAL_H
#define PLUGINCAMERAUEYE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PLUGINCAMERAUEYE_LIB
# define PLUGINCAMERAUEYE_EXPORT Q_DECL_EXPORT
#else
# define PLUGINCAMERAUEYE_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINCAMERAUEYE_GLOBAL_H
