#ifndef PARAMPLOTTERPLUGIN_GLOBAL_H
#define PARAMPLOTTERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PARAMPLOTTERPLUGIN_LIB
# define PARAMPLOTTERPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define PARAMPLOTTERPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // PARAMPLOTTERPLUGIN_GLOBAL_H
