#ifndef PLUGINPROJECT_GLOBAL_H
#define PLUGINPROJECT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PLUGINPROJECT_LIB
# define PLUGINPROJECT_EXPORT Q_DECL_EXPORT
#else
# define PLUGINPROJECT_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINPROJECT_GLOBAL_H
