#ifndef LINEARCOMBINATIONPLUGIN_GLOBAL_H
#define LINEARCOMBINATIONPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LINEARCOMBINATIONPLUGIN_LIB
# define LINEARCOMBINATIONPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define LINEARCOMBINATIONPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // LINEARCOMBINATIONPLUGIN_GLOBAL_H
