#ifndef SERIALCOMPORTPLUGIN_GLOBAL_H
#define SERIALCOMPORTPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SERIALCOMPORTPLUGIN_LIB
# define SERIALCOMPORTPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define SERIALCOMPORTPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // SERIALCOMPORTPLUGIN_GLOBAL_H
