#ifndef LISTSTEPPERPLUGIN_GLOBAL_H
#define LISTSTEPPERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LISTSTEPPERPLUGIN_LIBRARY)
#  define LISTSTEPPERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LISTSTEPPERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LISTSTEPPERPLUGIN_GLOBAL_H 