#ifndef PLUGINWAVELENGTHHIGHFINESSE_GLOBAL_H
#define PLUGINWAVELENGTHHIGHFINESSE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PLUGINWAVELENGTHHIGHFINESSE_LIB
# define PLUGINWAVELENGTHHIGHFINESSE_EXPORT Q_DECL_EXPORT
#else
# define PLUGINWAVELENGTHHIGHFINESSE_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINWAVELENGTHHIGHFINESSE_GLOBAL_H
